create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  status text not null default 'For Payment Verification',
  full_name text not null,
  batch_year integer not null,
  mobile_number text not null,
  email_address text not null,
  current_location text,
  registration_type text not null,
  total_attendees integer not null check (total_attendees > 0),
  guest_names jsonb not null default '[]'::jsonb,
  payment_method text not null,
  payment_name text not null,
  amount_paid numeric(10,2) not null check (amount_paid >= 0),
  payment_date date,
  transaction_reference text not null,
  proof_path text not null,
  proof_file_name text not null,
  payment_declaration boolean not null default false,
  data_consent boolean not null default false,
  submitted_at timestamptz not null default now()
);

alter table public.registrations enable row level security;

create index if not exists registrations_status_idx on public.registrations (status);
create index if not exists registrations_batch_year_idx on public.registrations (batch_year);
create index if not exists registrations_submitted_at_idx on public.registrations (submitted_at desc);
create unique index if not exists registrations_transaction_reference_unique_idx
  on public.registrations (lower(btrim(transaction_reference)));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-proofs',
  'payment-proofs',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'application/pdf']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- No public table or storage policies are created. All form writes go through
-- the trusted Bun server using the server-only service-role key.
